name: run scraper

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # voorkomt push-conflicten

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit changes if needed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # Alleen committen als er iets veranderd is
          if ! git diff --quiet; then
            if [ -f index.html ]; then git add index.html; fi
            if [ -f log.txt ]; then git add log.txt; fi
            git commit -m "Automatische update"
          else
            echo "Geen wijzigingen, geen commit"
          fi

      - name: Pull latest changes
        run: git pull --rebase

      - name: Push changes
        run
        : git push
