name: run scraper

on:
  schedule:
    - cron: "0 6 * * *"   # elke dag om 06:00
  workflow_dispatch:       # handmatig starten blijft mogelijk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit changes if needed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # Alleen committen als er iets veranderd is
          if ! git diff --quiet; then
            git add index.html log.txt
            git commit -m "Automatische update"
          else
            echo "Geen wijzigingen, geen commit"
          fi

      - name: Push changes
        run: git push
